// --------------------------- Fields ---------------------------
npc: moon/rathena/fields/amatsu.npc
npc: moon/rathena/fields/ayothaya.npc
npc: moon/rathena/fields/bifrost.npc
npc: moon/rathena/fields/comodo.npc
npc: moon/rathena/fields/einbroch.npc
npc: moon/rathena/fields/geffen.npc
npc: moon/rathena/fields/gonryun.npc
// npc: moon/rathena/fields/gw_fild.npc
npc: moon/rathena/fields/hugel.npc
npc: moon/rathena/fields/lighthalzen.npc
npc: moon/rathena/fields/louyang.npc
npc: moon/rathena/fields/lutie.npc
npc: moon/rathena/fields/manuk.npc
npc: moon/rathena/fields/mjolnir.npc
npc: moon/rathena/fields/morocc.npc
npc: moon/rathena/fields/moscovia.npc
npc: moon/rathena/fields/niflheim.npc
npc: moon/rathena/fields/payon.npc
npc: moon/rathena/fields/prontera.npc
npc: moon/rathena/fields/rachel.npc
npc: moon/rathena/fields/rockridge.npc
npc: moon/rathena/fields/splendide.npc
npc: moon/rathena/fields/umbala.npc
npc: moon/rathena/fields/veins.npc
npc: moon/rathena/fields/yuno.npc