// --------------------------------------------------------------
// -                        Job  Scripts                        -
// --------------------------------------------------------------

// ------------------------- Job Quests -------------------------
// - 1-1 Expanded
npc: moon/rathena/jobs/1-1e/gunslinger.txt
npc: moon/rathena/jobs/1-1e/ninja.txt
npc: moon/rathena/jobs/1-1e/taekwon.txt
// - 2-1
npc: moon/rathena/jobs/2-1/assassin.txt
npc: moon/rathena/jobs/2-1/blacksmith.txt
npc: moon/rathena/jobs/2-1/hunter.txt
npc: moon/rathena/jobs/2-1/knight.txt
npc: moon/rathena/jobs/2-1/priest.txt
npc: moon/rathena/jobs/2-1/wizard.txt
// - 2-1 Transcended
npc: moon/rathena/jobs/2-1a/AssassinCross.txt
npc: moon/rathena/jobs/2-1a/HighPriest.txt
npc: moon/rathena/jobs/2-1a/HighWizard.txt
npc: moon/rathena/jobs/2-1a/LordKnight.txt
npc: moon/rathena/jobs/2-1a/Sniper.txt
npc: moon/rathena/jobs/2-1a/WhiteSmith.txt
// - 2-1 Expanded
npc: moon/rathena/jobs/2-1e/StarGladiator.txt
// - 2-2
npc: moon/rathena/jobs/2-2/alchemist.txt
npc: moon/rathena/jobs/2-2/bard.txt
npc: moon/rathena/jobs/2-2/crusader.txt
npc: moon/rathena/jobs/2-2/dancer.txt
npc: moon/rathena/jobs/2-2/monk.txt
npc: moon/rathena/jobs/2-2/rogue.txt
npc: moon/rathena/jobs/2-2/sage.txt
// - 2-2 Transcended
npc: moon/rathena/jobs/2-2a/Champion.txt
npc: moon/rathena/jobs/2-2a/Clown.txt
npc: moon/rathena/jobs/2-2a/Creator.txt
npc: moon/rathena/jobs/2-2a/Gypsy.txt
npc: moon/rathena/jobs/2-2a/Paladin.txt
npc: moon/rathena/jobs/2-2a/Professor.txt
npc: moon/rathena/jobs/2-2a/Stalker.txt
// - 2-2 Expanded
npc: moon/rathena/jobs/2-2e/SoulLinker.txt
// - Novice
npc: moon/rathena/jobs/novice/supernovice.txt
// - Transcended Quest (2-x -> High Novice)
npc: moon/rathena/jobs/valkyrie.txt

// ------------------------ Skill Quests ------------------------
npc: moon/rathena/jopbs/acolyte_skills.txt
npc: moon/rathena/jopbs/alchemist_skills.txt
npc: moon/rathena/jopbs/archer_skills.txt
npc: moon/rathena/jopbs/assassin_skills.txt
npc: moon/rathena/jopbs/bard_skills.txt
npc: moon/rathena/jopbs/blacksmith_skills.txt
npc: moon/rathena/jopbs/crusader_skills.txt
npc: moon/rathena/jopbs/dancer_skills.txt
npc: moon/rathena/jopbs/hunter_skills.txt
npc: moon/rathena/jopbs/knight_skills.txt
npc: moon/rathena/jopbs/mage_skills.txt
npc: moon/rathena/jopbs/merchant_skills.txt
npc: moon/rathena/jopbs/monk_skills.txt
npc: moon/rathena/jopbs/novice_skills.txt
npc: moon/rathena/jopbs/priest_skills.txt
npc: moon/rathena/jopbs/rogue_skills.txt
npc: moon/rathena/jopbs/sage_skills.txt
npc: moon/rathena/jopbs/swordman_skills.txt
npc: moon/rathena/jopbs/thief_skills.txt
npc: moon/rathena/jopbs/wizard_skills.txt

// ------------------------- Job Quests -------------------------
// - 1-1
npc: moon/rathena/jobs/1-1/acolyte.txt
npc: moon/rathena/jobs/1-1/archer.txt
npc: moon/rathena/jobs/1-1/mage.txt
npc: moon/rathena/jobs/1-1/merchant.txt
npc: moon/rathena/jobs/1-1/swordman.txt
npc: moon/rathena/jobs/1-1/thief.txt
// - 1-1 Expanded
npc: moon/rathena/jobs/1-1e/taekwon.txt
// - 2-2
npc: moon/rathena/jobs/2-2/crusader.txt
// - Novice
// npc: moon/rathena/jobs/novice/academy.txt
// npc: moon/rathena/jobs/novice/novice.txt
// npc: moon/rathena/jobs/novice/supernovice_ex.txt
// - Job Repairs
// npc: moon/rathena/jobs/repair.txt
