#
# Table structure for table `item_db2`
#

DROP TABLE IF EXISTS `item_db2`;
CREATE TABLE `item_db2` (
  `id` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `name_aegis` varchar(50) DEFAULT NULL,
  `name_english` varchar(100) DEFAULT NULL,
  `type` varchar(20) DEFAULT NULL,
  `subtype` varchar(20) DEFAULT NULL,
  `price_buy` mediumint(8) UNSIGNED DEFAULT NULL,
  `price_sell` mediumint(8) UNSIGNED DEFAULT NULL,
  `weight` smallint(5) UNSIGNED DEFAULT NULL,
  `attack` smallint(5) UNSIGNED DEFAULT NULL,
  `defense` smallint(5) UNSIGNED DEFAULT NULL,
  `range` tinyint(2) UNSIGNED DEFAULT NULL,
  `slots` tinyint(2) UNSIGNED DEFAULT NULL,
  `job_all` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_acolyte` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_alchemist` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_archer` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_assassin` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_barddancer` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_blacksmith` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_crusader` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_gunslinger` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_hunter` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_knight` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_mage` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_merchant` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_monk` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_ninja` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_novice` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_priest` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_rogue` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_sage` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_soullinker` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_stargladiator` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_supernovice` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_swordman` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_taekwon` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_thief` tinyint(1) UNSIGNED DEFAULT NULL,
  `job_wizard` tinyint(1) UNSIGNED DEFAULT NULL,
  `class_all` tinyint(1) UNSIGNED DEFAULT NULL,
  `class_normal` tinyint(1) UNSIGNED DEFAULT NULL,
  `class_upper` tinyint(1) UNSIGNED DEFAULT NULL,
  `class_baby` tinyint(1) UNSIGNED DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `location_head_top` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_head_mid` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_head_low` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_armor` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_right_hand` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_left_hand` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_garment` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_shoes` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_right_accessory` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_left_accessory` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_costume_head` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_costume_head_top` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_costume_head_mid` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_costume_head_low` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_costume_garment` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_ammo` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_shadow_armor` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_shadow_weapon` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_shadow_shield` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_shadow_shoes` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_shadow_right_accessory` tinyint(1) UNSIGNED DEFAULT NULL,
  `location_shadow_left_accessory` tinyint(1) UNSIGNED DEFAULT NULL,
  `weapon_level` tinyint(1) UNSIGNED DEFAULT NULL,
  `armor_level` tinyint(1) UNSIGNED DEFAULT NULL,
  `equip_level_min` smallint(5) UNSIGNED DEFAULT NULL,
  `equip_level_max` smallint(5) UNSIGNED DEFAULT NULL,
  `refineable` tinyint(1) UNSIGNED DEFAULT NULL,
  `view` smallint(5) UNSIGNED DEFAULT NULL,
  `alias_name` varchar(50) DEFAULT NULL,
  `flag_buyingstore` tinyint(1) UNSIGNED DEFAULT NULL,
  `flag_deadbranch` tinyint(1) UNSIGNED DEFAULT NULL,
  `flag_container` tinyint(1) UNSIGNED DEFAULT NULL,
  `flag_uniqueid` tinyint(1) UNSIGNED DEFAULT NULL,
  `flag_bindonequip` tinyint(1) UNSIGNED DEFAULT NULL,
  `flag_dropannounce` tinyint(1) UNSIGNED DEFAULT NULL,
  `flag_noconsume` tinyint(1) UNSIGNED DEFAULT NULL,
  `flag_dropeffect` varchar(20) DEFAULT NULL,
  `delay_duration` bigint(20) UNSIGNED DEFAULT NULL,
  `delay_status` varchar(30) DEFAULT NULL,
  `stack_amount` smallint(5) UNSIGNED DEFAULT NULL,
  `stack_inventory` tinyint(1) UNSIGNED DEFAULT NULL,
  `stack_cart` tinyint(1) UNSIGNED DEFAULT NULL,
  `stack_storage` tinyint(1) UNSIGNED DEFAULT NULL,
  `stack_guildstorage` tinyint(1) UNSIGNED DEFAULT NULL,
  `nouse_override` smallint(5) UNSIGNED DEFAULT NULL,
  `nouse_sitting` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_override` smallint(5) UNSIGNED DEFAULT NULL,
  `trade_nodrop` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_notrade` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_tradepartner` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_nosell` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_nocart` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_nostorage` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_noguildstorage` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_nomail` tinyint(1) UNSIGNED DEFAULT NULL,
  `trade_noauction` tinyint(1) UNSIGNED DEFAULT NULL,
  `script` text DEFAULT NULL,
  `equip_script` text DEFAULT NULL,
  `unequip_script` text DEFAULT NULL,
  `equip_locations` int(10) UNSIGNED GENERATED ALWAYS AS (coalesce(`location_head_low`,0) * 1 + coalesce(`location_right_hand`,0) * 2 + coalesce(`location_garment`,0) * 4 + coalesce(`location_right_accessory`,0) * 8 + coalesce(`location_armor`,0) * 16 + coalesce(`location_left_hand`,0) * 32 + coalesce(`location_shoes`,0) * 64 + coalesce(`location_left_accessory`,0) * 128 + coalesce(`location_head_top`,0) * 256 + coalesce(`location_head_mid`,0) * 512 + coalesce(`location_costume_head_top`,0) * 1024 + coalesce(`location_costume_head_mid`,0) * 2048 + coalesce(`location_costume_head_low`,0) * 4096 + coalesce(`location_costume_garment`,0) * 8192 + coalesce(`location_ammo`,0) * 32768 + coalesce(`location_shadow_armor`,0) * 65536 + coalesce(`location_shadow_weapon`,0) * 131072 + coalesce(`location_shadow_shield`,0) * 262144 + coalesce(`location_shadow_shoes`,0) * 524288 + coalesce(`location_shadow_right_accessory`,0) * 1048576 + coalesce(`location_shadow_left_accessory`,0) * 2097152) VIRTUAL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
