// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),
	// [Stingor]
	ACMD_DEF(sellstuff),
	ACMD_DEF(sellitem),
	ACMD_DEF(showspeed),
	ACMD_DEF(mvpcard),
	ACMD_DEF(fastmove),
	ACMD_DEF(attackskill),
	ACMD_DEF(aoeskill),
	ACMD_DEF(sitstand),
	ACMD_DEF(moche),
	ACMD_DEF(celebrate),
	ACMD_DEF(trollolol),
	ACMD_DEF(untrollolol),
	ACMD_DEF(playertalk),
	ACMD_DEF(autolootmvp),
	ACMD_DEF(autolootmvpreward),
	ACMD_DEF(autolootrare),
	ACMD_DEF(autolootpognon),
	ACMD_DEF(stats),
	ACMD_DEF(shopsearch),
	ACMD_DEF(wings),
	ACMD_DEF(storagealt),
	ACMD_DEF2("storagealt1", storagealt),
	ACMD_DEF2("storagealt2", storagealt),
	ACMD_DEF2("storagealt3", storagealt),
	ACMD_DEF2("storagealt4", storagealt),
	ACMD_DEF2("storagealt5", storagealt),
	ACMD_DEF(storecard),
	ACMD_DEF(partybuff), // [Vykimo]
