// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/
	// Stingor
	int item_drop_equip_mvp_min,item_drop_equip_mvp_max;
	int item_drop_equip_boss_min,item_drop_equip_boss_max;
	int gm_aspd;
	int homunc_teleport_acd;
	int aoe_teleport_acd;
	int refresh_acd;
	int paladin_sacri_max_hp;
	int all_sacri_max_hp;
	int emp_heal_hp;
	int emp_sanctu_hp;
	int emp_potionpitch_hp;
	int disable_edp_berserk;
	int pvp_gtb_nerf;
	int cap_delay_rate;
	int gm_delay_rate;
	int gm_auto_hide;
	int st_vulture_nerf;
	int gtb_dispell_nerf;
	int gtb_nodispell_preserve;
	int no_skill_emp;
	int item_use_interval_pvp;
	int hp_percent_pvp_nerf;
	int sp_percent_pvp_nerf;
	int kaizel_cd;
	int maxstatlevelcalc;
	int testsource;
	int azuranerfsp;
	int nj_issenstr;
	int jump_kick_pcnerf;
	int hatred_pcnerf;
	int esma_pcnerf;
	int nerf_bloodybranch;
	int up_spawnmvp;
	int max_hp_lkberserk;
	int dispell_knowledge;
	int debugscriptcont;
	int piercevitdef;
	int vulcanpvphit;
	int crystalizenerf;
	int burningnerf;
	int newcarttermform;
	int heal_rate;
	int unlockcrit;
	int shopx1,shopx2,shopy1,shopy2;
	int setcellnovend;
	int nerfdstrafestalk;
	int lukimmunefreeze;
	int mdefimmunefreeze;
	int enablenpceventwarn;
	int healgtb;
	int mult_eventexp;
	int mult_eventdrop;
	int debugpos;
