// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/
	// Stingor
	int32 item_drop_equip_mvp_min,item_drop_equip_mvp_max;
	int32 item_drop_equip_boss_min,item_drop_equip_boss_max;
	int32 gm_aspd;
	int32 homunc_teleport_acd;
	int32 aoe_teleport_acd;
	int32 refresh_acd;
	int32 paladin_sacri_max_hp;
	int32 all_sacri_max_hp;
	int32 emp_heal_hp;
	int32 emp_sanctu_hp;
	int32 emp_potionpitch_hp;
	int32 pvp_gtb_nerf;
	int32 cap_delay_rate;
	int32 gm_delay_rate;
	int32 gm_auto_hide;
	int32 st_vulture_nerf;
	int32 gtb_dispell_nerf;
	int32 gtb_nodispell_preserve;
	int32 no_skill_emp;
	int32 item_use_interval_pvp;
	int32 hp_percent_pvp_nerf;
	int32 sp_percent_pvp_nerf;
	int32 kaizel_cd;
	int32 maxstatlevelcalc;
	int32 testsource;
	int32 azuranerfsp;
	int32 nj_issenstr;
	int32 jump_kick_pcnerf;
	int32 hatred_pcnerf;
	int32 esma_pcnerf;
	int32 nerf_bloodybranch;
	int32 up_spawnmvp;
	int32 max_hp_lkberserk;
	int32 dispell_knowledge;
	int32 piercevitdef;
	int32 vulcanpvphit;
	int32 crystalizenerf;
	int32 burningnerf;
	int32 newcarttermform;
	int32 heal_rate;
	int32 unlockcrit;
	int32 shopx1,shopx2,shopy1,shopy2;
	int32 setcellnovend;
	int32 nerfdstrafestalk;
	int32 lukimmunefreeze;
	int32 mdefimmunefreeze;
	int32 enablenpceventwarn;
	int32 healgtb;
	int32 mult_eventexp;
	int32 mult_eventdrop;
	int32 debugpos;
