// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

#ifndef CONFIG_CUSTOM_DEFINES_POST_HPP
#define CONFIG_CUSTOM_DEFINES_POST_HPP

/**
 * rAthena configuration file (http://rathena.org)
 * For detailed guidance on these check http://rathena.org/wiki/SRC/config/
 **/



enum e_inviteminfo : uint8 {
	INVITEMINFO_NAMEID = 0,
	INVITEMINFO_IDX,
	INVITEMINFO_AMOUNT,
	INVITEMINFO_EQUIP,
	INVITEMINFO_REFINE,
	INVITEMINFO_IDENTIFY,
	INVITEMINFO_ATTRIBUTE,
	INVITEMINFO_EXPIRE,
	INVITEMINFO_BOUND,
	INVITEMINFO_ENCHANTGRADE,
	INVITEMINFO_TRADABLE,
	INVITEMINFO_FAVORITE,
	INVITEMINFO_CARD1,
	INVITEMINFO_CARD2,
	INVITEMINFO_CARD3,
	INVITEMINFO_CARD4,
	INVITEMINFO_OPTION_ID1,
	INVITEMINFO_OPTION_VALUE1,
	INVITEMINFO_OPTION_PARAM1,
	INVITEMINFO_OPTION_ID2,
	INVITEMINFO_OPTION_VALUE2,
	INVITEMINFO_OPTION_PARAM2,
	INVITEMINFO_OPTION_ID3,
	INVITEMINFO_OPTION_VALUE3,
	INVITEMINFO_OPTION_PARAM3,
	INVITEMINFO_OPTION_ID4,
	INVITEMINFO_OPTION_VALUE4,
	INVITEMINFO_OPTION_PARAM4,
	INVITEMINFO_OPTION_ID5,
	INVITEMINFO_OPTION_VALUE5,
	INVITEMINFO_OPTION_PARAM5,
};

#endif /* CONFIG_CUSTOM_DEFINES_POST_HPP */
