// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder
	
	/* Stingor */
	export_constant(MAX_LEVEL_BASE_EXP);
	export_constant(MAX_LEVEL_JOB_EXP);
	export_constant(MF_NODUEL);
	export_constant(MF_NOATTACKSKILL);
	export_constant(MF_NOAOESKILL);
	export_constant(MF_NOMVPCARD);
	export_constant(MF_NOBBRANCH);
	export_constant(MF_NOMAIL);
	export_constant(MF_NODISGUISE);

	export_constant(IG_AUTOLOOTRARE);
	export_constant(IG_SELLITEM);
	export_constant(IG_SELLSTUFF);

	export_constant2("bAspd2", SP_ASPD2);
	export_constant2("bDelayrate2", SP_DELAYRATE2);
	export_constant2("bNoAmmo",SP_NO_AMMO);
	export_constant2("bNoBottle",SP_NO_BOTTLE);
	export_constant2("bNoItem",SP_NO_ITEM);
	export_constant2("bNoZeny",SP_NO_ZENY);

	export_constant(INVITEMINFO_NAMEID);
	export_constant(INVITEMINFO_IDX);
	export_constant(INVITEMINFO_AMOUNT);
	export_constant(INVITEMINFO_EQUIP);
	export_constant(INVITEMINFO_REFINE);
	export_constant(INVITEMINFO_IDENTIFY);
	export_constant(INVITEMINFO_ATTRIBUTE);
	export_constant(INVITEMINFO_EXPIRE);
	export_constant(INVITEMINFO_BOUND);
	export_constant(INVITEMINFO_ENCHANTGRADE);
	export_constant(INVITEMINFO_TRADABLE);
	export_constant(INVITEMINFO_FAVORITE);
	export_constant(INVITEMINFO_CARD1);
	export_constant(INVITEMINFO_CARD2);
	export_constant(INVITEMINFO_CARD3);
	export_constant(INVITEMINFO_CARD4);
	export_constant(INVITEMINFO_OPTION_ID1);
	export_constant(INVITEMINFO_OPTION_VALUE1);
	export_constant(INVITEMINFO_OPTION_PARAM1);
	export_constant(INVITEMINFO_OPTION_ID2);
	export_constant(INVITEMINFO_OPTION_VALUE2);
	export_constant(INVITEMINFO_OPTION_PARAM2);
	export_constant(INVITEMINFO_OPTION_ID3);
	export_constant(INVITEMINFO_OPTION_VALUE3);
	export_constant(INVITEMINFO_OPTION_PARAM3);
	export_constant(INVITEMINFO_OPTION_ID4);
	export_constant(INVITEMINFO_OPTION_VALUE4);
	export_constant(INVITEMINFO_OPTION_PARAM4);
	export_constant(INVITEMINFO_OPTION_ID5);
	export_constant(INVITEMINFO_OPTION_VALUE5);
	export_constant(INVITEMINFO_OPTION_PARAM5);
