// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder
	
	/* Stingor */
	export_constant(MF_NODUEL);
	export_constant(MF_NOATTACKSKILL);
	export_constant(MF_NOAOESKILL);
	export_constant(MF_NOMVPCARD);
	export_constant(MF_NOBBRANCH);
	export_constant(MF_NOMAIL);
	export_constant(MF_NODISGUISE);

	export_constant(IG_AUTOLOOTRARE);
	export_constant(IG_SELLITEM);
	export_constant(IG_SELLSTUFF);

	export_constant2("bAspd2", SP_ASPD2);
	export_constant2("bDelayrate2", SP_DELAYRATE2);
	export_constant2("bNoAmmo",SP_NO_AMMO);
	export_constant2("bNoBottle",SP_NO_BOTTLE);
	export_constant2("bNoItem",SP_NO_ITEM);
	export_constant2("bNoZeny",SP_NO_ZENY);
