// --------------------------------------------------------------
// -                         Map  Flags                         -
// --------------------------------------------------------------
npc: npc/rathena/mapflag/nopvp.txt
npc: npc/rathena/mapflag/gvg.txt
npc: npc/rathena/mapflag/gvg_noparty.txt
npc: npc/rathena/mapflag/hidemobhpbar.txt
npc: npc/rathena/mapflag/jail.txt
npc: npc/rathena/mapflag/nightmare.txt
npc: npc/rathena/mapflag/noicewall.txt
npc: npc/rathena/mapflag/nomemo.txt
npc: npc/rathena/mapflag/nopenalty.txt
npc: npc/rathena/mapflag/nosave.txt
npc: npc/rathena/mapflag/noteleport.txt
npc: npc/rathena/mapflag/noreturn.txt
npc: npc/rathena/mapflag/noskill.txt
npc: npc/rathena/mapflag/nowarp.txt
npc: npc/rathena/mapflag/nowarpto.txt
npc: npc/rathena/mapflag/partylock.txt
npc: npc/rathena/mapflag/privateairship.txt
npc: npc/rathena/mapflag/pvp.txt
npc: npc/rathena/mapflag/pvp_noparty.txt
npc: npc/rathena/mapflag/pvp_noguild.txt
npc: npc/rathena/mapflag/night.txt
npc: npc/rathena/mapflag/reset.txt
npc: npc/rathena/mapflag/restricted.txt
npc: npc/rathena/mapflag/battleground.txt
npc: npc/rathena/mapflag/skill_damage.txt
npc: npc/rathena/mapflag/town.txt
npc: npc/rathena/mapflag/nocostume.txt
npc: npc/rathena/mapflag/skill_duration.txt
