// --------------------------------------------------------------
// -                      Monster  Scripts                      -
// --------------------------------------------------------------

npc: npc/rathena/mobs/academy.txt
npc: npc/rathena/mobs/championmobs.txt
npc: npc/rathena/mobs/int_land.txt
npc: npc/rathena/mobs/jail.txt
npc: npc/rathena/mobs/prt_cas.txt
npc: npc/rathena/mobs/pvp.txt
npc: npc/rathena/mobs/towns.txt
npc: npc/rathena/mobs/verus.txt

// --------------------------- Fields ---------------------------
npc: npc/rathena/mobs/fields/amatsu.txt
npc: npc/rathena/mobs/fields/ayothaya.txt
npc: npc/rathena/mobs/fields/bifrost.txt
npc: npc/rathena/mobs/fields/brasilis.txt
npc: npc/rathena/mobs/fields/comodo.txt
npc: npc/rathena/mobs/fields/dewata.txt
npc: npc/rathena/mobs/fields/dicastes.txt
npc: npc/rathena/mobs/fields/eclage.txt
npc: npc/rathena/mobs/fields/einbroch.txt
npc: npc/rathena/mobs/fields/geffen.txt
npc: npc/rathena/mobs/fields/gonryun.txt
npc: npc/rathena/mobs/fields/hugel.txt
npc: npc/rathena/mobs/fields/lighthalzen.txt
npc: npc/rathena/mobs/fields/louyang.txt
npc: npc/rathena/mobs/fields/lutie.txt
npc: npc/rathena/mobs/fields/malaya.txt
npc: npc/rathena/mobs/fields/manuk.txt
npc: npc/rathena/mobs/fields/mjolnir.txt
npc: npc/rathena/mobs/fields/morocc.txt
npc: npc/rathena/mobs/fields/moscovia.txt
npc: npc/rathena/mobs/fields/niflheim.txt
npc: npc/rathena/mobs/fields/payon.txt
npc: npc/rathena/mobs/fields/prontera.txt
npc: npc/rathena/mobs/fields/rachel.txt
npc: npc/rathena/mobs/fields/rockridge.txt
npc: npc/rathena/mobs/fields/splendide.txt
npc: npc/rathena/mobs/fields/umbala.txt
npc: npc/rathena/mobs/fields/veins.txt
npc: npc/rathena/mobs/fields/yuno.txt