// --------------------------------------------------------------
// -                         Guild Wars                         -
// --------------------------------------------------------------

// ----------------------- War of Emperium ----------------------
// - Guild WoE time settings
// npc: npc/rathena/guild/agit_controller.txt 
// - Guild NPC Template file
// npc: npc/rathena/guild/agit_main.txt
// - Al De Baran
// npc: npc/rathena/guild/aldeg_cas01.txt
// npc: npc/rathena/guild/aldeg_cas02.txt
// npc: npc/rathena/guild/aldeg_cas03.txt
// npc: npc/rathena/guild/aldeg_cas04.txt
// npc: npc/rathena/guild/aldeg_cas05.txt
// - Geffen
// npc: npc/rathena/guild/gefg_cas01.txt
// npc: npc/rathena/guild/gefg_cas02.txt
// npc: npc/rathena/guild/gefg_cas03.txt
// npc: npc/rathena/guild/gefg_cas04.txt
// npc: npc/rathena/guild/gefg_cas05.txt
// - Payon
// npc: npc/rathena/guild/payg_cas01.txt
// npc: npc/rathena/guild/payg_cas02.txt
// npc: npc/rathena/guild/payg_cas03.txt
// npc: npc/rathena/guild/payg_cas04.txt
// npc: npc/rathena/guild/payg_cas05.txt
// - Prontera
// npc: npc/rathena/guild/prtg_cas01.txt
// npc: npc/rathena/guild/prtg_cas02.txt
// npc: npc/rathena/guild/prtg_cas03.txt
// npc: npc/rathena/guild/prtg_cas04.txt
// npc: npc/rathena/guild/prtg_cas05.txt
// - Treasure Room Protection
// npc: npc/rathena/guild/trs_rp.txt

// --------------- War of Emperium Second Edition ---------------
// - WoE SE time settings
// npc: npc/rathena/guild2/agit_start_se.txt
// - Guild NPC Template file
// npc: npc/rathena/guild2/agit_main_se.txt
// - Town Flags
// npc: npc/rathena/guild2/guild_flags.txt
// - Arunafeltz
// npc: npc/rathena/guild2/arug_cas01.txt
// npc: npc/rathena/guild2/arug_cas02.txt
// npc: npc/rathena/guild2/arug_cas03.txt
// npc: npc/rathena/guild2/arug_cas04.txt
// npc: npc/rathena/guild2/arug_cas05.txt
// - Schwaltzvalt
// npc: npc/rathena/guild2/schg_cas01.txt
// npc: npc/rathena/guild2/schg_cas02.txt
// npc: npc/rathena/guild2/schg_cas03.txt
// npc: npc/rathena/guild2/schg_cas04.txt
// npc: npc/rathena/guild2/schg_cas05.txt

// --------------------------------------------------------------
// -                     Renewal Guild Wars                     -
// --------------------------------------------------------------

// ----------------------- War of Emperium ----------------------
// - Hall of Abyss
// npc: npc/rathena/guild/invest_main.txt
// npc: npc/rathena/guild/invest_npc.txt

// npc: npc/rathena/guild3/agit_main_te.txt
// npc: npc/rathena/guild3/agit_start_te.txt
// npc: npc/rathena/guild3/te_aldecas1.txt
// npc: npc/rathena/guild3/te_aldecas2.txt
// npc: npc/rathena/guild3/te_aldecas3.txt
// npc: npc/rathena/guild3/te_aldecas4.txt
// npc: npc/rathena/guild3/te_aldecas5.txt
// npc: npc/rathena/guild3/te_prtcas01.txt
// npc: npc/rathena/guild3/te_prtcas02.txt
// npc: npc/rathena/guild3/te_prtcas03.txt
// npc: npc/rathena/guild3/te_prtcas04.txt
// npc: npc/rathena/guild3/te_prtcas05.txt

// - Guild Mission
// npc: npc/rathena/guild/mission_main.txt
// npc: npc/rathena/guild/mission_npc.txt
