// --------------------------------------------------------------
// -                      Monster  Scripts                      -
// --------------------------------------------------------------

npc: npc/rathena/mobs/academy.txt
npc: npc/rathena/mobs/championmobs.txt
npc: npc/rathena/mobs/int_land.txt
npc: npc/rathena/mobs/jail.txt
npc: npc/rathena/mobs/prt_cas.txt
npc: npc/rathena/mobs/pvp.txt
npc: npc/rathena/mobs/towns.txt
npc: npc/rathena/mobs/verus.txt

// -------------------------- Dungeons --------------------------
npc: npc/rathena/mobs/dungeons/abbey.txt
npc: npc/rathena/mobs/dungeons/abyss.txt
npc: npc/rathena/mobs/dungeons/alde_dun.txt
npc: npc/rathena/mobs/dungeons/ama_dun.txt
npc: npc/rathena/mobs/dungeons/anthell.txt
npc: npc/rathena/mobs/dungeons/ayo_dun.txt
npc: npc/rathena/mobs/dungeons/beach_dun.txt
npc: npc/rathena/mobs/dungeons/bra_dun.txt
npc: npc/rathena/mobs/dungeons/c_tower.txt
npc: npc/rathena/mobs/dungeons/dew_dun.txt
npc: npc/rathena/mobs/dungeons/dic_dun.txt
npc: npc/rathena/mobs/dungeons/ecl_tdun.txt
npc: npc/rathena/mobs/dungeons/ein_dun.txt
npc: npc/rathena/mobs/dungeons/gef_dun.txt
npc: npc/rathena/mobs/dungeons/gefenia.txt
npc: npc/rathena/mobs/dungeons/glastheim.txt
npc: npc/rathena/mobs/dungeons/gld_dunSE.txt
npc: npc/rathena/mobs/dungeons/gld_re.txt
npc: npc/rathena/mobs/dungeons/gon_dun.txt
npc: npc/rathena/mobs/dungeons/ice_dun.txt
npc: npc/rathena/mobs/dungeons/in_sphinx.txt
npc: npc/rathena/mobs/dungeons/iz_dun.txt
npc: npc/rathena/mobs/dungeons/juperos.txt
npc: npc/rathena/mobs/dungeons/kh_dun.txt
npc: npc/rathena/mobs/dungeons/lhz_dun.txt
npc: npc/rathena/mobs/dungeons/lou_dun.txt
npc: npc/rathena/mobs/dungeons/ma_dun.txt
npc: npc/rathena/mobs/dungeons/mag_dun.txt
npc: npc/rathena/mobs/dungeons/mal_dun.txt
npc: npc/rathena/mobs/dungeons/mjo_dun.txt
npc: npc/rathena/mobs/dungeons/moc_pryd.txt
npc: npc/rathena/mobs/dungeons/moro_vol.txt
npc: npc/rathena/mobs/dungeons/mosk_dun.txt
npc: npc/rathena/mobs/dungeons/nyd_dun.txt
npc: npc/rathena/mobs/dungeons/odin.txt
npc: npc/rathena/mobs/dungeons/orcsdun.txt
npc: npc/rathena/mobs/dungeons/pay_dun.txt
npc: npc/rathena/mobs/dungeons/prt_maze.txt
npc: npc/rathena/mobs/dungeons/prt_prison.txt
npc: npc/rathena/mobs/dungeons/prt_q.txt
npc: npc/rathena/mobs/dungeons/prt_sew.txt
npc: npc/rathena/mobs/dungeons/ra_san.txt
npc: npc/rathena/mobs/dungeons/rockridge.txt
npc: npc/rathena/mobs/dungeons/teg_dun.txt
npc: npc/rathena/mobs/dungeons/tha_t.txt
npc: npc/rathena/mobs/dungeons/thor_v.txt
npc: npc/rathena/mobs/dungeons/treasure.txt
npc: npc/rathena/mobs/dungeons/tur_dun.txt
npc: npc/rathena/mobs/dungeons/xmas_dun.txt
npc: npc/rathena/mobs/dungeons/yggdrasil.txt

// --------------------------- Fields ---------------------------
npc: npc/rathena/mobs/fields/amatsu.txt
npc: npc/rathena/mobs/fields/ayothaya.txt
npc: npc/rathena/mobs/fields/bifrost.txt
npc: npc/rathena/mobs/fields/brasilis.txt
npc: npc/rathena/mobs/fields/comodo.txt
npc: npc/rathena/mobs/fields/dewata.txt
npc: npc/rathena/mobs/fields/dicastes.txt
npc: npc/rathena/mobs/fields/eclage.txt
npc: npc/rathena/mobs/fields/einbroch.txt
npc: npc/rathena/mobs/fields/geffen.txt
npc: npc/rathena/mobs/fields/gonryun.txt
npc: npc/rathena/mobs/fields/hugel.txt
npc: npc/rathena/mobs/fields/lighthalzen.txt
npc: npc/rathena/mobs/fields/louyang.txt
npc: npc/rathena/mobs/fields/lutie.txt
npc: npc/rathena/mobs/fields/malaya.txt
npc: npc/rathena/mobs/fields/manuk.txt
npc: npc/rathena/mobs/fields/mjolnir.txt
npc: npc/rathena/mobs/fields/morocc.txt
npc: npc/rathena/mobs/fields/moscovia.txt
npc: npc/rathena/mobs/fields/niflheim.txt
npc: npc/rathena/mobs/fields/payon.txt
npc: npc/rathena/mobs/fields/prontera.txt
npc: npc/rathena/mobs/fields/rachel.txt
npc: npc/rathena/mobs/fields/rockridge.txt
npc: npc/rathena/mobs/fields/splendide.txt
npc: npc/rathena/mobs/fields/umbala.txt
npc: npc/rathena/mobs/fields/veins.txt
npc: npc/rathena/mobs/fields/yuno.txt